### ISSUE TITLE
Lightning Email Validation

### ISSUE THREAD

**Issue by NickEckert** [RohanNagar/lightning#31]
Lightning needs to validate an email by sending an email to a newly registered user or newly registered email for an existing user. Once Lightning can validate that a user has access to the registered email the registration process can finish or an email can be added as a valid address for the account.

The process will go something like this:
1. Start the validation process by creating a new user and denoting the associated email as unverified. If the user already exists then just add a new email as unverified.
2. Generate a unique hash and store it along side the unconfirmed field in the DB.
3. Append the hash as a query param to a url that points to a validation endpoint on Lightning and send the url to the address you want to validate.
4. When lightning receives an email with a hash, parse the hash and confirm the user is associated with the given hash.
5. Mark the email as valid in thunder.

Note that a user account can be viewed as unverified if there exists only one email and it's not verified. This can be useful for tracking down accounts that are registered but never verified.

The end goal is to allow account recovery and general contact with our user base.

- [ ] Add email validation field associated with each unique address in the DB
- [ ] Add email random hash associated with each unique address in the DB
- [ ] Ability to generate a random hash to store in the DB
- [ ] Ability to create a URL containing an emails associated hash value as a query param
- [ ] Ability to parse the URL containing a hash value and verify it belongs to a certain users email
- [ ] Ability to mark individual user emails as invalid/valid
- [ ] Ability to store an associated hash value along with each unique email on a user account

**Comment by RohanNagar** [comment]
Moved to thunder/#21
